CREATE DATABASE QLKHACHSAN
GO
USE QLKHACHSAN
GO
CREATE TABLE QLIDANGNHAP
(
	TENDN NVARCHAR(20) NOT NULL PRIMARY KEY,
	MKDN NVARCHAR(20),
	LOAINGUOIDUNG NVARCHAR(50), 
)
CREATE TABLE DANGNHAPADMIN
(
	TENAM NVARCHAR(20) NOT NULL PRIMARY KEY,
	MKAM NVARCHAR(20), 
)
insert into DANGNHAPADMIN
values
('thao','1234')
go
CREATE TABLE DOANHTHU
(
	MADOANHTHU NVARCHAR(20) NOT NULL PRIMARY KEY,
	THANG INT,
	TONGDOANHTHU FLOAT,
)
CREATE TABLE QUYDINH
(
	TENQUYDINH NVARCHAR(50) NOT NULL PRIMARY KEY,
	MOTA NVARCHAR(50),
)
CREATE TABLE KHACHHANG
(
	MAKHACH NVARCHAR(20) NOT NULL PRIMARY KEY,
	TENKHACH NVARCHAR(50),
	CMNN NVARCHAR(10),
	DIACHI NVARCHAR(50),
	DIENTHOAI NVARCHAR(12),
	GIOITINH NVARCHAR(5),
	QUOCTICH NVARCHAR(50),
)
select * from KHACHHANG
CREATE TABLE LOAIDICHVU
(
	MALOAIDV NVARCHAR(20) NOT NULL PRIMARY KEY,
	TENLOAIDV NVARCHAR(50),
)
CREATE TABLE DICHVU
(
	MADV NVARCHAR(20) NOT NULL PRIMARY KEY,
	MALOAIDV NVARCHAR(20),
	DONVI NVARCHAR(50),
	DONGIA FLOAT,
	CONSTRAINT FK_DV_MLDV FOREIGN KEY(MALOAIDV) REFERENCES LOAIDICHVU(MALOAIDV),
)
CREATE TABLE PHONGBAN
(
	MAPB NVARCHAR(20) NOT NULL PRIMARY KEY,
	TENPB NVARCHAR(50),
	DIACHI NVARCHAR(50),
	SDT NVARCHAR(12),
)
go
insert into PHONGBAN
values 
('PhongVS','Phong Ve Sinh','Tang 1 Toa Nha','012345456')
go
CREATE TABLE NHANVIEN
(
	MANHANVIEN NVARCHAR(20) NOT NULL PRIMARY KEY,
	MAPB NVARCHAR(20),
	TENNHANVIEN NVARCHAR(50),
	CMNN NVARCHAR(10),
	GIOITINH NVARCHAR(5),
	QUENQUAN NVARCHAR(50),
	DIENTHOAI NVARCHAR(12),
	DANTOC NVARCHAR(50),
	CHUCVU NVARCHAR(50),
	LUONG FLOAT,
	CONSTRAINT FK_NV_PB FOREIGN KEY(MAPB) REFERENCES PHONGBAN(MAPB),
)
go
insert into NHANVIEN
values 
('nv01','Phongvs','nguyen van thao','1111111111',N'Nữ','aaaaaaaaaaa','11111111111','kinh','giamdoc',17000000)
go
select MANHANVIEN,TENPB,TENNHANVIEN,CMNN,GIOITINH,QUENQUAN,DIENTHOAI,DANTOC,CHUCVU,LUONG 
from NHANVIEN,PHONGBAN
where NHANVIEN.MAPB=PHONGBAN.MAPB

select MANHANVIEN,TENPB,TENNHANVIEN,CMNN,GIOITINH,QUENQUAN,DIENTHOAI,DANTOC,CHUCVU,LUONG from NHANVIEN,PHONGBAN where NHANVIEN.MAPB=PHONGBAN.MAPB and TENPB LIKE N'%Phong%'
go
CREATE TABLE LOAIPHONG
(
	MALOAIPHONG NVARCHAR(20) NOT NULL PRIMARY KEY,
	TENLOAIPHONG NVARCHAR(50),
	DONGIA FLOAT,
	SONGUOICHUAN INT,
	SONGUOITOIDA INT,
)
go
insert into LOAIPHONG
values
('Thuong01','Thuong 1 giuong',100000,1,2)
insert into LOAIPHONG
values
('Vip01','Vip 1 giuong',100000,1,2)
go
SELECT * FROM LOAIPHONG WHERE MALOAIPHONG LIKE N'%Thuong%'
go
CREATE TABLE PHONG
(
	MAPHONG NVARCHAR(20) NOT NULL PRIMARY KEY,
	MALOAIPHONG NVARCHAR(20),
	MANHANVIEN NVARCHAR(20),
	TINHTRANG NVARCHAR(50),
	GHICHU NVARCHAR(50),
	CONSTRAINT FK_P_MLP FOREIGN KEY(MALOAIPHONG) REFERENCES LOAIPHONG(MALOAIPHONG),
	CONSTRAINT FK_P_NV FOREIGN KEY(MANHANVIEN) REFERENCES NHANVIEN(MANHANVIEN),
)
go
insert into PHONG
values
('PHONG01T1','Thuong01','nv01','Trong','Phong Thuong')
go
select * from PHONG
go
select MAPHONG,TENLOAIPHONG,TENNHANVIEN,TINHTRANG,GHICHU  from PHONG,LOAIPHONG,NHANVIEN where PHONG.MALOAIPHONG=LOAIPHONG.MALOAIPHONG and PHONG.MANHANVIEN=NHANVIEN.MANHANVIEN
go
CREATE TABLE THIETBI
(
	MATHIETBI NVARCHAR(20) NOT NULL PRIMARY KEY,
	TENTHIETBI NVARCHAR(50),
	MAPHONG NVARCHAR(20),
	SL INT,
	CONSTRAINT FK_TB_P FOREIGN KEY(MAPHONG) REFERENCES PHONG(MAPHONG),
)
insert into THIETBI
values
('Guong','Guong Doi','PHONG01T1',1)
--DANH SACH DAT PHONG
CREATE TABLE DATPHONG
(
	MADAT NVARCHAR(20) NOT NULL PRIMARY KEY,
	MAKHACH NVARCHAR(20),
	CONSTRAINT FK_DP_KHACH FOREIGN KEY(MAKHACH) REFERENCES KHACHHANG(MAKHACH),
)
go
INSERT INTO DATPHONG
VALUES
('DATPHONG01','KHACHHANG01')
INSERT INTO DATPHONG
VALUES
('DATPHONG02','KHACHHANG01')
SElECt MADAT from DATPHONG where MAKHACH='KHACHHANG02'
Select * from DATPHONG
select * from CHITIETDATPHONG
go
CREATE TABLE CHITIETDATPHONG
(
	MADAT NVARCHAR(20) NOT NULL,
	MAPHONG NVARCHAR(20) NOT NULL,
	NGAYDANGKI DATETIME,
	NGAYNHANDUKIEN DATETIME,
	CONSTRAINT PK_CTDP PRIMARY KEY(MADAT,MAPHONG),
)
GO
SET DATEFORMAT YMD
INSERT INTO CHITIETDATPHONG
VALUES 
('DATPHONG01','Thuong01',2,'7/10/2020','10/10/2000')

SET DATEFORMAT YMD
INSERT INTO CHITIETDATPHONG
VALUES 
('DATPHONG02','vip01',2,'7/10/2020','10/10/2000')
INSERT INTO CHITIETDATPHONG
VALUES 
('DATPHONG04','vip01',2,'7/10/2020','10/10/2000')
DELETE CHITIETDATPHONG

Select * from CHITIETDATPHONG Where MADAT= 'Datphong01'
GO
SELECT * FROM CHITIETDATPHONG 
CREATE TABLE NHANPHONG
(
	MANHANPHONG NVARCHAR(20) NOT NULL PRIMARY KEY,
	MADAT NVARCHAR(20),
	MAKHACH NVARCHAR(20),
)
GO
CREATE TABLE CHITIETNHANPHONG
(
	MANHANPHONG NVARCHAR(20) NOT NULL,
	MAPHONG NVARCHAR(20)NOT NULL,
	TENKHACH NVARCHAR(50),
	CMNN NVARCHAR(10),
	NGAYNHAN DATETIME,
	NGAYTRADUKIEN DATETIME,
	NGAYTRATHUCTE DATETIME,
)
CREATE TABLE DANHSACHSUDUNGDICHVU
(
	MASDDV NVARCHAR(20) NOT NULL PRIMARY KEY,
	MADV NVARCHAR(20),
	MANHANPHONG NVARCHAR(20),
	SL INT,
)
CREATE TABLE HOADON
(
	MAHOADON NVARCHAR(20) NOT NULL PRIMARY KEY,
	NHANVIENLAP NVARCHAR(50),
	MAKHACH NVARCHAR(20),
	MANHANPHONG NVARCHAR(20) ,
	TONGTIEN FLOAT,
	NGAYLAP DATETIME,	
	CONSTRAINT FK_HD_KHACH FOREIGN KEY(MAKHACH) REFERENCES KHACHHANG(MAKHACH),
	CONSTRAINT FK_HD_DV FOREIGN KEY(MADV) REFERENCES DICHVU(MADV),
)
SET DATEFORMAT DMY
INSERT INTO HOADON
VALUES 
('HD01','Nguyen Van Thao','KHACHHANG01','DV01',370000,'10/10/2000')
go
select * from Hoadon where NHANVIENLAP LIKE N'%N%'
go
CREATE TABLE CHITIETHOADON
(
	MAHOADON NVARCHAR(20) NOT NULL,
	MAPHONG NVARCHAR(20) NOT NULL,
	MASDDV NVARCHAR(20) NOT NULL,
	TIENPHONG FLOAT,
	TIENDICHVU FLOAT,
	GIAMGIAKH INT,
	SONGAY INT,
	HINHTHUCTHANHTOAN NVARCHAR(50),	
	CONSTRAINT PK_CTHD PRIMARY KEY(MAHOADON,MAPHONG),
)
INSERT INTO CHITIETHOADON
VALUES 
('HD01','PHONG01T1',100000,170000,0,0,2,'Tien Mat')
ALTER TABLE CHITIETDATPHONG
ADD CONSTRAINT FK_CTDP_DP FOREIGN KEY(MADAT) REFERENCES DATPHONG(MADAT)
ALTER TABLE CHITIETDATPHONG
ADD	CONSTRAINT FK_CTDP_LP FOREIGN KEY(MALOAIPHONG) REFERENCES LOAIPHONG(MALOAIPHONG)
ALTER TABLE CHITIETHOADON
ADD CONSTRAINT FK_CTHD_HD FOREIGN KEY(MAHOADON) REFERENCES HOADON(MAHOADON)
ALTER TABLE CHITIETHOADON
ADD	CONSTRAINT FK_CTHD_P FOREIGN KEY(MAPHONG) REFERENCES PHONG(MAPHONG)
GO 
INSERT INTO QLIDANGNHAP(TENDN,MKDN,LOAINGUOIDUNG)
VALUES
('thaocutepro','123456','Admin'),
('tuyencutepro','123456','Admin'),
('thao','123456789','User'),
('tuyen','123456789','User') 
go
INSERT INTO KHACHHANG
VALUES
('KHACHHANG01',N'NGUYỄN VĂN THẢO','012345678',N'BÌNH TÂN','0363046205','NAM',N'VIỆT NAM')
INSERT INTO KHACHHANG
VALUES
('KHACHHANG02',N'NGUYỄN VĂN THAO','012345678',N'BÌNH TÂN','0363046205','NAM',N'VIỆT NAM')
INSERT INTO KHACHHANG
VALUES
('KHACHHANG03',N'Hiếu','012345678',N'Tân Phú','0363046205',N'Bê Đê',N'Mỹ')
select * from khachhang

SELECT * FROM KHACHHANG WHERE TENKHACH=N'NGUYỄN VĂN THẢO'
SELECT * FROM KHACHHANG WHERE DIACHI Like N'%B%'

INSERT INTO QUYDINH
VALUES 
('QD01',N'HÚT THUỐC RA NGOÀI BAN CÔNG TRÁNH CHÁY')

INSERT INTO QUYDINH
VALUES 
(N'KHÔNG ĐƯỢC HÚT THUỐC',N'HÚT THUỐC RA NGOÀI BAN CÔNG TRÁNH CHÁY')

INSERT INTO LOAIDICHVU
VALUES 
('LOAIDV01','BAR')

INSERT INTO LOAIDICHVU
VALUES 
('LOAIDV02','An Sang')

INSERT INTO DICHVU
VALUES
('DV01','LOAIDV01','DEM',170000)

INSERT INTO DICHVU
VALUES
('DV02','LOAIDV02','sang',170000)

select *  from  dichvu,LOAIDICHVU where DICHVU.MALOAIDV=LOAIDICHVU.MALOAIDV and LOAIDICHVU.TENLOAIDV = N'BAR'
SELECT * FROM DICHVU,LOAIDICHVU WHERE DICHVU.MALOAIDV=LOAIDICHVU.MALOAIDV and LOAIDICHVU.TENLOAIDV like '%b%'
 SELECT TENLOAIDV FROM DICHVU,LOAIDICHVU WHERE DICHVU.MALOAIDV=LOAIDICHVU.MALOAIDV

 select MADV,TENLOAIDV,DONVI,DONGIA  from  dichvu,LOAIDICHVU where DICHVU.MALOAIDV=LOAIDICHVU.MALOAIDV

 select MALOAIDV from  LOAIDICHVU where TENLOAIDV = 'BAR'

 select MALOAIDV  from LOAIDICHVU where TENLOAIDV ='BAR'

 select MAPHONG,PHONG.MALOAIPHONG,LOAIPHONG.TENLOAIPHONG,PHONG.MANHANVIEN,NHANVIEN.TENNHANVIEN,TINHTRANG,GHICHU  from PHONG,LOAIPHONG,NHANVIEN where PHONG.MALOAIPHONG=LOAIPHONG.MALOAIPHONG and PHONG.MANHANVIEN=NHANVIEN.MANHANVIEN

 select *  from PHONG